version: "3.9"
services:
  tgbot:
    container_name: MollaKeyboardi
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          cpus: '0.025'
          memory: 100M